flarum/lang-english

- flarum.json
The "language" icon is better and more specific by default than the
"globe" icon, which can be used on many non-language extensions.
> Change the Font Awesome icon

- .editorconfig
- .gitattributes
- .gitignore
Add .editorconfig for consistent coding styles, normalize line endings and export-ignore (ensure to normalize line endings to Unix (LF) and exclude some extra files which are uncessary to the extension itself when exporting an archive) and ignore junks files to be added (it includes common OS junk files, some common backup and log files and ensure that .git is ignored).
> Standardization

- icon.svg
The original markup was checked as XML. New changes make it valid as valid SVG 1.1.
I also replaced the original tab indent to a two spaces indent for Flarum's coding standards.
> Valid SVG 1.1 Markup

- README.md
Current instructions of the README.mf file are wrong because the L10n process changed a lot. I changed these instructions with more generic ones for now.
> Update translating instructions

- locale/core.yml
- Adds new sub-keys to replace key prefixes, and adjusts key names accordingly.
- Moves several button strings from `admin.permissions_` to `admin.permissions_controls`
- Merges `forum.settings_notify_` strings into `forum.settings`
- Rolls `forum.user_avatar_` strings into `forum.user`
- Moves the `user_deleted_text` to the `lib` namespace.
- Adds four other leftover strings to the `lib` namespace.
- Includes minor changes to formatting and comments.
> Group translation keys by sub-key instead of prefix

- locale/flarum-flags.yml
See [flarum/core #265](https://github.com/flarum/core/issues/265)
Please don't merge! Will be adding further commits.
> Reorganize key names for Flags

- locale/flarum-lock.yml
> Reorganize key names for Lock

- locale/flarum-lock.yml
- Fixes several key name errors in PR #14.
- Adds missing comment for `post_stream`.
> Fix key names in Lock

- locale/flarum-pusher.yml
> Reorganize key names for Pusher

- locale/core.yml
- locale/flarum-lock.yml
- Shortens two key names for consistency with `badge:` namespace.
- Supports https://github.com/flarum/core/pull/601
- Supports https://github.com/flarum/lock/pull/4
> Rename keys for badge tooltips

- locale/flarum-sticky.yml
> Reorganize key names for Sticky

- locale/flarum-sticky.yml
- Adds a reused string and two references
- Sorry, should have caught this before the PR!
> Clean up reused "sticky" string

- locale/flarum-subscriptions.yml
> Reorganize key names for Subscriptions

- locale/flarum-flags.yml
- locale/flarum-sticky.yml
- Fixes commenting on two files where I accidentally used an old version.
> Revise "reused strings" commenting to match core

- locale/flarum-subscriptions.yml
- locale/flarum-tags.yml
- Supports https://github.com/flarum/tags/pull/22.
- (Also adjusts one string in **flarum-subscriptions.yml**.)
> Reorganize key names for Tags

- locale/flarum-mentions.yml
- Adds comments to indicate pluralizable strings.
- Supports https://github.com/flarum/mentions/pull/12.
> Reorganize key names for Mentions

- locale/flarum-likes.yml
- Adds a comment to indicate a pluralizable string.
- Supports https://github.com/flarum/likes/pull/3.
> Reorganize key names for Likes

- locale/core.yml
- locale/flarum-mentions.yml
Two strings use *Reply*, it's not necessary to translate it twice.
The addition of the newly `core.ref.reply` reused string fix that.
> Merge Reply references into a reused string

- locale/flarum-mentions.yml
- Adds a comment to indicate a pluralizable string.
- Supports https://github.com/flarum/mentions/pull/13.
> Pluralize the post mentioned notification string

- locale/core.yml
- locale/flarum-likes.yml
- locale/flarum-mentions.yml
- Merges two strings from Likes and Mentions into the core YML.
- Adds commenting to core YML to indicate strings referenced by extensions.
- Changes `others_link` to `others_text` in Mentions.
- Removes obsolete `ref:` namespace from Mentions.
> Merge reused strings into core

- locale/flarum-likes.yml
- Adds a comment to indicate a pluralizable string.
- Supports https://github.com/flarum/likes/commit/e867b54.
> Pluralize the post liked notification string

- composer.json
The English language pack is for Flarum and can't be used without it, so I don't see why to not add Flarum's Core as requirement, as extensions.
> Add Flarum's Core as a requirement

- locale/core.yml
This string is also used in the **Following** page when there are no discussions followed by the user. In that case, it doesn't helps the user to create a new discussion (he just can't create a followed discussion anyway). To prevent a new string to be added just for that, I think it's better to remove the question and display a generic message.
> Do not ask to create a new discussion anymore

- locale/core.yml
- locale/flarum-flags.yml
- locale/flarum-likes.yml
- locale/flarum-lock.yml
- locale/flarum-mentions.yml
- locale/flarum-pusher.yml
- locale/flarum-sticky.yml
- locale/flarum-subscriptions.yml
- locale/flarum-tags.yml
- Moves `ref` below `email`, adjacent to `group`.
- Deletes block comment for `email` namespace.
- Adds detail to block comment for `group`.
- Changes "string" to "translation" in all files.
> English revamp for i18n docs

- locale/core.yml
Forgot the double quotes around a translation with HTML tags. Sorry!
> Adds required double quotes to a translation.

- locale/flarum-tags.yml
Part of fix for flarum/core#330
This PR adds a language key for the PermissionGrid in the admin area.
There is a new setting to set how long a author can edit the tags for his discussion. This adds a translation key for it.
> Added language key for allowing edit of tags. 

- locale/core.yml
- Adds three translations for this placeholder dialog.
- Updates the instructions to mention Composer.
- Supports https://github.com/flarum/core/pull/752.
> Add translations for the Add Extension modal

- locale/core.yml
- Adds language resources extracted from `reset.blade.php`.
- Moves `basic` key namespace to `views`.
- Subdivides `views` namespace based on filename.
- Supports [#918](https://github.com/flarum/core/pull/918).
> Fix unextracted translations in core blade files.

- locale/core.yml
This are the translations for flarum/core#933 (or https://github.com/flarum/core/commit/dd0dc44dd833460862272eb4d63b84e0763b2722)
Added:
```yml
email:
heading: => core.ref.email
text: Configure the SMTP settings and addresses your forum will use to send email.
server_heading: SMTP Server
driver_label: Driver
host_label: Host
port_label: Port
encryption_label: Encryption
account_heading: SMTP Account
username_label: Username
password_label: Password
adresses_heading: Adresses
from_label: Sender
submit_button: => core.ref.save_changes
```
and this (on `core.admin.nav`)
```yml
email_button: => core.ref.email
email_text: Configure your forum's email settings.
```
> Admin SMTP UI Translations

- locale/core.yml
- Removes two obsolete keys from the Extensions page.
- Corrects the suffix on a key in the Change Email modal.
- Extracts the title of the Edit User modal.
- Reorders keys in `core.email` namespace.
- Supports flarum/core/pull/964.
> Clean up translation keys

- locale/flarum-tags.yml
- Adds `:attribute` values for use in `validation.between.numeric`.
- Partially solves flarum/core#973.
- Lines 118 and 134 of [this file](https://github.com/flarum/flarum-ext-tags/blob/d0b62510d8a1a9d3a38cfdad0ed8447e85c5f7b0/src/Listener/SaveTagsToDatabase.php) need to be revised to use these phrases.
> Add translations for API error messages

- locale/flarum-subscriptions.yml
- locale/flarum-tags.yml
- Adjusts the key for the "Follow after reply" setting.
- Supports flarum/flarum-ext-subscriptions/pull/10.
- Moves `api:` section below `views:`.
> Adjust ID key name and move API key

- locale/core.yml
These strings contain commas and should be quoted.
Source: http://symfony.com/doc/current/components/yaml/yaml_format.html#strings
> Quote strings with special or reserved characters

- locale/flarum-tags.yml
- locale/validation.yml
- Moves attributes added in #79 to `validation.yml`.
- See flarum/core#973.
- `SaveTagsToDatabase.php` needs to be revised to use these phrases.
- Caution: key names have been changed as well!
> Move attributes to validation

- locale/flarum/akismet.yml
- locale/flarum/approval.yml
- locale/flarum/auth-facebook.yml
- locale/flarum/auth-github.yml
- locale/flarum/auth-twitter.yml
- locale/flarum/core.yml
- locale/flarum/flags.yml
- locale/flarum/likes.yml
- locale/flarum/lock.yml
- locale/flarum/mentions.yml
- locale/flarum/pusher.yml
- locale/flarum/sticky.yml
- locale/flarum/subscriptions.yml
- locale/flarum/suspend.yml
- Removes existing first-level prefix and de-dents files.
- Adjusts key references to use new namespacing.
- Pluralizes the `group` scope prefix in `core.yml`.
- Adjusts one reference in `core.yml` to match.
> Adjust namespacing for everything else

- locale/core.yml
Just because there are now two references of it.
> Add "Rename" to the reused translations

- locale/flarum-flags.yml
Changed "{username} flagged" to "Flagged by {username}" and  
"{username} flagged as {reason}" to "{username} flagged this as {reason}"
> flagged_by text grammar fix

- locale/core.yml
Due to https://github.com/flarum/flarum-ext-english/commit/476ba8b0946005fdc3767f4dbae34fc5996664e5 (the comma was the special character which needed double quotes before its removal)
> Remove unnecessary double quotes

- locale/validation.yml
Add message for "Not Regex" validation rule (https://github.com/laravel/laravel/commit/293fae6bd8285d076cedf2b8147a20e4090aa5bc#diff-9c04f727a922ad4f105b9ad764ec221d) and add language lines for the newly added comparison validation rules (https://github.com/laravel/laravel/commit/51507a6d8aef31fadac8125663f83f3302405a72#diff-9c04f727a922ad4f105b9ad764ec221d and https://github.com/laravel/laravel/commit/7d8e91ab66d0e8cba4e24394f6340109fbce024e#diff-9c04f727a922ad4f105b9ad764ec221d).
> Update to the latest Laravel version

- locale/core.yml
- locale/flarum-suspend.yml
- locale/flarum-tags.yml
on second thought, don't you think keys with multiple lines value (e.g `core.email.activate_account.body`) should have more weight, and be sorted alphabetically after non-multiple line values?
> [WIP] sort keys

- locale/flarum-suspend.yml
Related to flarum/flarum-ext-suspend#11 & flarum/flarum-ext-suspend#20.
flarum/flarum-ext-suspend#20 must be merged for the translations to work.
19 years is when I suspended the user indefinitely (until 01/01/2038).
> [Suspend] Add translations for notifications

- locale/core.yml
As reported by @Hiobi on the French language pack ([see commit](https://github.com/milescellar/lang-french/commit/416cbd9da9e0ed1beda69a5cdd1f8b1702c9b60b)).
> Fix translation sorting

- locale/core.yml
This commit makes a bit clearer the fact that the permission serves to override the privacy settings of users. Without the "Always" word, one might think that the permission is required for users to see each other's last seen time in general, which is not true.
> Improve the "last seen time" permission text

- locale/core.yml
Companion PR to https://github.com/flarum/core/pull/2023
> Added translations for Send Test Mail feature

- locale/validation.yml
See: https://github.com/laravel/laravel/commit/050c1d880ec1d48ef40d7a0f2b2f1040c23cebb9
> Add new password rule language line

- locale/core.yml
Please see: https://symfony.com/doc/current/components/yaml/yaml_format.html#strings
> Strings containing specific characters must be quoted

- composer.json
- locale/core.yml
- locale/flarum-tags.yml
Added the translation keys for my AdminUx PR https://github.com/flarum/core/pull/2409
> AdminUx translation additions

- locale/validation.yml
Source: https://github.com/laravel/laravel/blob/b46c16b4246c7dc648158221c49f5b2e785e7c30/resources/lang/en/validation.php#L36
I'm not sure where did `:other`  come from.
> Fix `date_format` message in validation.yml
