flarum/lang-english

locale/core.yml

See flarum/core#265
- Fixes namespacing of reorganized core keys (flarum/core#563)
- Includes strings for the admin interface (flarum/core#575)
- Includes a couple of leftover core strings (flarum/core#577)

Update core YML with extracted strings

---

.editorconfig
.gitattributes
.gitignore

As we know, these files will be used for translators, who are not developers.
To be more friendly, I commented all the code from the extra files to explain what each action does.
I also added the SVG line ending normalization.

Comment the code (and add SVG LF support)

---

locale/core.yml

- Adds a `lib.badge` namespace to match extension handling.

Add namespacing for badges

---

locale/flarum-lock.yml
locale/validation.yml

There was two newline at the end of the file. This patch removes the extra newline.

Remove extra newline

---

locale/flarum-flags.yml

- Fixes a few key name errors in PR #13

Fix key names in Flags

---

locale/flarum-tags.yml

Use "OK" for submit button in Choose Tags modal

---

locale/flarum-likes.yml

- Adds a key I overlooked in the reorganization.

Add an "others" key for Likes notifications

---

locale/core.yml
locale/flarum-flags.yml
locale/flarum-subscriptions.yml
locale/flarum-tags.yml

Quotes are required when the string contains special or reserved characters (`:`, `{`, `}`, `[`, `]`, `,`, `&`, `*`, `#`, `?`, `|`, `-`, `<`, `>`, `=`, `!`, `%`, `@`, and `\`).
See:
http://symfony.com/doc/current/components/yaml/yaml_format.html#strings

Quote values with special or reserved characters

---

locale/core.yml

- Adds a comment to indicate use by Tags extension

Add comment to core.ref.okay

---

locale/validation.yml

Update the file with the latest Laravel addition (and its fix):
- https://github.com/laravel/laravel/commit/8a49b4f137003a91496de52ea4f48781802b2afb
- https://github.com/laravel/laravel/commit/f8e58cedb2b7a877208d17ad1aad7c8b77639d11

Add "required_unless" lang line

---

locale/core.yml
locale/flarum-tags.yml

- Adds resources in support of flarum/core#645.
- Also fixes a few comments in the core and Tags resources.

Extract leftover strings

---

locale/flarum-auth-facebook.yml
locale/flarum-auth-github.yml
locale/flarum-auth-twitter.yml

- Adds resources to support flarum/auth-facebook#1.
- Adds resources to support flarum/auth-github#1.
- Adds resources to support flarum/auth-twitter#1.

Add translations for Flarum Auth extensions

---

locale/core.yml
locale/flarum-approval.yml
locale/flarum-suspend.yml

- Adds resources to support flarum/approval#1.
- Adds resources to support flarum/suspend#2.
- Updates a comment in core language resources.

Add translations for Approval and Suspend

---

locale/flarum-akismet.yml

- Adds resources to support flarum/akismet#1.

Add translations for Akismet

---

locale/flarum-suspend.yml

- Fixes a copypasta translation in Suspend.
- Thanks to @maelsoucaze for proofreading, as always!

Fix translations

---

locale/core.yml
locale/flarum-likes.yml
locale/flarum-mentions.yml
locale/flarum-suspend.yml
locale/flarum-tags.yml

- Adjusts namespacing in support of flarum/core#648.
- Corrects key alphabetization in a few locale files.

Clean up locale files

---

locale/core.yml

For fix https://github.com/flarum/core/issues/679

Added "Are you sure you want to mark all notifications as read?"

---

locale/flarum-mentions.yml

Add Quote button translation for mentions

---

locale/validation.yml

See: https://github.com/laravel/laravel/pull/3775

Add language line for image dimensions validation rule

---

locale/validation.yml

See: https://github.com/laravel/laravel/commit/cd032040441787c827aa07c428ae753281b685df

Add language line for file validation rule

---

locale/validation.yml

Laravel's related commits: https://github.com/laravel/laravel/commit/537b6288fba5181bff6011facecbf05b6de0bbb0 https://github.com/laravel/laravel/commit/dd1e64a7a4cdcec6c846aed13330d6523d457b91 https://github.com/laravel/laravel/commit/1562407562859a880f5f494647d5c52f8af8d44e and https://github.com/laravel/laravel/commit/7da6edf8c14772f14ff11616199fb16bd19909ae

Update to the latest Laravel version

---

locale/flarum/tags.yml

- Removes existing first-level prefix and de-dents file.
- Adjusts key references to use new namespacing.

Adjust namespacing for Tags

---

locale/validation.yml

See: https://github.com/laravel/laravel/commit/fa1eae35b9ce5bd278cbc85571be2474192181de

Add language lines for before_or_equal and after_or_equal

---

locale/core.yml

Associated with: https://github.com/flarum/core/pull/1094

Add missing translation

---

locale/core.yml

Add missing and new translations (after the fixing PR 1093 of flarum/core).

add missing translations (for EditUserModal.js)

---

locale/validation.yml

Source: https://github.com/laravel/laravel/commit/90886732cf6df6d8694287c3f9d92496a4f1c61b

Update description of filled rule

---

locale/validation.yml

Source: https://github.com/laravel/laravel/commit/7e5739d266bba4624f933f547f111ee6ad26e095

Add IPv4/IPv6 validation messages

---

icon.svg

The SVG now weighs 259 bytes only (27.45% saving).

Optimize Union Jack SVG with SVGO

---

locale/core.yml

Add `core.admin.permissions.view_user_list_label` from flarum/core#1190

Add view user list locale

---

locale/core.yml

Related to flarum/core#1106
Closes flarum/core#1192

Add `core.admin.basics.show_language_selector_label`

---

locale/core.yml

Related to flarum/core#1267 and flarum/core#1315
Before, it was in flarum/flarum-ext-english#111 .
I thought it has been merged, so i update my fork with this repo head, which automatically close the MR. And then i see it wasnt merged yet. So, i recreate the MR here.

Custom Footer HTML Translations

---

locale/core.yml
locale/flarum-statistics.yml
locale/flarum-tags.yml

[See the discussion about these changes.](https://github.com/flarum/flarum-ext-english/pull/114)

Use reused translations and remove unnecessary double quotes

---

locale/core.yml
locale/flarum-tags.yml

See https://github.com/flarum/flarum-ext-tags/pull/50

New translation for tags extension (related to tags extension PR)

---

.travis.yml
scripts/linter.sh

more info about yamllinter:
https://github.com/sijad/yaml-translation-utils/tree/master/yamllinter

add yamllinter check

---

bootstrap.php

Simplify the bootstrap file

---

locale/validation.yml

Fix from https://github.com/laravel/laravel/commit/7ff917aa203b2f0869761c99283d18b6a2eb6cf8#diff-9c04f727a922ad4f105b9ad764ec221d

Fix alpha_dash

---

locale/core.yml

Companion PR for https://github.com/flarum/core/pull/1466

Separate edit and delete posts translation

---

locale/core.yml

Add `core.forum.user.posts_empty_text`

---

locale/core.yml

Add view user last seen at label

---

locale/validation.yml

See: https://github.com/laravel/laravel/commit/c96995fb61632c6da0d7fc13cf6fd16a57f6c5ec#diff-9c04f727a922ad4f105b9ad764ec221d

Add message for UUID validation rule

---

locale/validation.yml

See: https://github.com/laravel/laravel/commit/93c687418963f7c99b641fda905015054c785eb4#diff-9c04f727a922ad4f105b9ad764ec221d

Add ends_with validation message

---

locale/core.yml

Related to pull request https://github.com/flarum/core/pull/1859

Add translation for Edit User Permission

---

locale/core.yml

PR with locale for flarum/core#1874.

Add mark as read notification tooltip

---

locale/flarum-markdown.yml

image_tooltip for markdown

---

locale/core.yml

https://github.com/flarum/core/pull/2174

Companion changes for Display name driver

---

locale/core.yml

See https://github.com/flarum/core/issues/495

Add 'all discussions' meta title

---

locale/flarum-subscriptions.yml

https://github.com/flarum/subscriptions/pull/30

Translate emails for subscriptions

---

locale/core.yml

For https://github.com/flarum/core/pull/2188

Add extension dependency error translations

---

locale/core.yml

Inform the user that their edit has been made

---

locale/core.yml

Added Core Configuration header name.
ref: https://github.com/flarum/core/pull/2468

AdminUX Small Patch Translations

---

locale/flarum-tags.yml

Add bypass tag requirements permission label
